In [1]:
#Task 1

In [23]:
# 1. Write a function to compute 5/0 and use try/except to catch the exceptions.

def divide(a,b):
    try:
        result= a/b
        print("The Computation of " + str(a) + "/" + str(b) + " is: ", result)
    except:
        print("The Computation of " + str(a) + "/" + str(b) + " was not possible.")

divide(5,0)

The Computation of 5/0 was not possible.


In [18]:
# 2. Implement a Python program to generate all sentences where subject is in ["Americans",
#   "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

#  Hint: Subject,Verb and Object should be declared in the program as shown below.

#  subjects=["Americans ","Indians"]
#  verbs=["play","watch"]
#  objects=["Baseball","Cricket"]

subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

sentence = [' '.join([i,j,k]) for i in subjects for j in verbs for k in objects]
for s in sentence:
    print(s)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [4]:
#Task 2

In [15]:
# 1. Write a function so that the columns of the output matrix are powers of the input vector.
#    The order of the powers is determined by the increasing boolean argument. Specifically, when
#    increasing is False, the i-th output column is the input vector raised element-wise to the power
#    of N - i - 1.
   
#    HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.


import numpy as np

def vander_vector_fn(x,N, increasing):
    x = np.array(x)
    if x.ndim != 1:
        print("x must be a one-dimensional array or sequence.")
        
    v = np.empty((len(x), N), dtype=np.promote_types(x.dtype, int))
    tmp = v[:, ::-1] if not increasing else v

    if N > 0:
        tmp[:, 0] = 1
    if N > 1:
        tmp[:, 1:] = x[:, None]
        np.multiply.accumulate(tmp[:, 1:], out=tmp[:, 1:], axis=1)
    return v

x=np.array([1,2,3,4,5])

N=4
print("*********** x=['1,2,3,4,5'] & N=4 & Increasing=True ***********")
print(vander_vector_fn(x,N,True))

print("\n\n*********** x=['1,2,3,4,5'] & N=4 & Increasing=False ***********")
print(vander_vector_fn(x,N,False))

N=5
print("\n\n*********** x=['1,2,3,4,5'] & N=5 & Increasing=True ***********")
print(vander_vector_fn(x,N,True))

print("\n\n*********** x=['1,2,3,4,5'] & N=5 & Increasing=False ***********")
print(vander_vector_fn(x,N,False))

*********** x=['1,2,3,4,5'] & N=4 & Increasing=True ***********
[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]


*********** x=['1,2,3,4,5'] & N=4 & Increasing=False ***********
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]


*********** x=['1,2,3,4,5'] & N=5 & Increasing=True ***********
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]


*********** x=['1,2,3,4,5'] & N=5 & Increasing=False ***********
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
